#!/bin/bash
# PreToolUse(Edit|Write): block hand-editing generated migration files.
# Migrations are generated by your migration tool and are write-once — editing them
# (or their snapshot/journal metadata) corrupts the diff chain and breaks the next
# generate. See .claude/rules/database.md.
#
# The pattern below matches a `migrations/` or `drizzle/` path segment. Adjust it to
# your tool's directory:
#   - Drizzle: its `out` dir (often `drizzle/` or `migrations/`)
#   - Prisma:  `prisma/migrations/`
#   - Knex:    `migrations/`
file_path=$(jq -r '.tool_input.file_path // ""')
if echo "$file_path" | grep -qE '(^|/)(migrations|drizzle)/'; then
  echo "Blocked: files under a migrations directory are generated and write-once. Edit the schema and run your tool's generate command instead (see .claude/rules/database.md). If this path is not a generated migrations dir, adjust .claude/hooks/block-manual-migrations.sh." >&2
  exit 2
fi
exit 0
