#!/bin/bash
# PreToolUse(Edit|Write): block writes to secrets, lockfiles, .git, and generated files.
file_path=$(jq -r '.tool_input.file_path // ""')

case "$file_path" in
  *.env|*.env.*|*/.env|*/.env.*|*.lock|*/.git/*)
    echo "Blocked: cannot write to .env files, lockfiles, or the .git directory. To change dependencies run 'npm install'." >&2
    exit 2
    ;;
esac

# routeTree.gen.ts is generated by the TanStack Router plugin on dev/build.
if echo "$file_path" | grep -qE 'routeTree\.gen\.ts$'; then
  echo "Blocked: routeTree.gen.ts is generated by the TanStack Router plugin. Do not edit it by hand — add/rename files under src/routes and it regenerates." >&2
  exit 2
fi

exit 0
